// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Book of Challenges - Napoli Edition",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Book of Challenges - Napoli Edition",
            targets: ["App"],
            bundleIdentifier: "com.challenge.choose",
            teamIdentifier: "T66N85ZKBW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: "public.app-category.books"
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            path: "App"
        )
    ]
)
